apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: clustermanageraddons.addon.open-cluster-management.io
spec:
  group: addon.open-cluster-management.io
  names:
    kind: ClusterManagerAddOn
    listKind: ClusterManagerAddOnList
    plural: clustermanageraddons
    singular: clustermanageraddon
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  "validation":
    "openAPIV3Schema":
      description: ClusterManagerAddOn represents the registration of an addon It
        allows the user to discover which addon is available for the cluster manager.
        It provide a linkage from ClusterManagerAddOn to ManagedClusterAddOn The name
        of the ClusterManagerAddOn resource will be the use for the namespace scoped
        ManagedClusterAddon resource It also provides metadata information about the
        addon. ClusterManagerAddOn is a cluster scoped resource.
      type: object
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Spec represents a desired configuration for the agent on the
            cluster manager addon
          type: object
          properties:
            addOnConfigCRD:
              description: AddOnConfigCRD is the name for the CRD name of the addon
                CRs, which is used for addon configurations. It will inform the user
                which resource the add-on controller/operator will use to control
                the addon.
              type: string
            description:
              description: Description represents the detailed description of the
                addon.
              type: string
            displayName:
              description: DisplayName represents the name that will be displayed.
              type: string
        status:
          description: Status represents the current status of cluster manager addon
          type: object
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
